Structure: Ducks 

Models:
  - User:

    CRUD: false
  
    Slice:
      - FirstName: string
      - LastName: string
      - email: string
      - token: string
      - isLoggedIn: boolean

    Actions: 
      - login
      - register

    Thunks:
      - loginThunk:
          - /login
          - login
      - registerThunk:
          - /signup
          - login
