"use strict";
exports.__esModule = true;
var NodeID3 = require('node-id3');
var testFolder = './tests/';
var fs = require('fs');
var resolve = require('path').resolve;
var suffixTrie_1 = require("./suffixTrie");
var files = fs.readdirSync(resolve(__dirname, "./public/tunes"));
var theTrie = new suffixTrie_1["default"](files);
console.log(theTrie.containsString(process.argv[2]));
