#!/usr/bin/env bash

# etc nginx config that couldn't get handled in first install script

sudo rm /etc/nginx/sites-enabled/default
tee -a /etc/nginx/sites-available << END
server {
  listen 80;
  server_name engine;
  location / {
    proxy_set_header  X-Real-IP  $remote_addr;
    proxy_set_header  Host       $http_host;
    proxy_pass        http://127.0.0.1:3000;
  }
} 
END
sudo ln -s /etc/nginx/sites-available/engine /etc/nginx/sites-enabled/engine
sudo service nginx restart
sudo echo "configged nginx"
